name: teranga
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  country_picker: ^2.0.20
  pinput: ^2.2.31
  image_picker: ^0.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/food1.jpg
    - assets/images/food2.jpg
    - assets/images/food3.jpg
    - assets/icons/welcome.png
    - assets/icons/delivery.png
    - assets/icons/image4.png
    - assets/icons/image5.png
    - assets/icons/last.png
    - assets/icons/catgories.png
    - assets/icons/register.png
    - assets/icons/otp.png
  

  
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
